### PR TITLE
GraphClassWithShortestPathMethod

### LINKED ISSUE #1: Dijkastra Algorithm needed as Class
the class graph should be there and Dijkstra as it's a member function. 
which prints the shortest path. of the given source to destination

### PR DESCRIPTION
**Pull request by solanki2899**

### CODE REVIEW

**Review by pradeexsu — APPROVED** [review]

**Comment by solanki2899** [comment]
I have made the required changes. pls check it.

**Review by pradeexsu — APPROVED** [review]

**Comment by pradeexsu** [comment]
Good job

**Comment by solanki2899** [comment]
hey pradeep i dont know why but in hactoberfest profile, your repo is
considered as ineligible repo. can you pls check it.?

[image: image.png]

**Comment by pradeexsu** [comment]
this might be because I also participated in the same feast.

**Comment by pradeexsu** [comment]
sorry for that.

**Comment by solanki2899** [comment]
Ohh it doesn't matter, begginers never mind 😅

**Comment by pradeexsu** [comment]
@solanki2899  hay check it should be valid for hacktoberfest

**Pull request merged**
